name: DWH_Cole
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - anyio==4.4.0
      - apispec==6.6.1
      - argcomplete==3.5.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - blinker==1.8.2
      - cachelib==0.9.0
      - cachetools==5.5.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clickclick==20.10.2
      - colorama==0.4.6
      - colorlog==6.8.2
      - configupdater==3.2
      - connexion==2.14.2
      - cron-descriptor==1.4.5
      - croniter==3.0.3
      - cryptography==42.0.8
      - deprecated==1.2.14
      - dill==0.3.1.1
      - dnspython==2.6.1
      - docutils==0.16
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - flask==2.2.5
      - flask-appbuilder==4.5.0
      - flask-babel==2.0.0
      - flask-caching==2.3.0
      - flask-jwt-extended==4.6.0
      - flask-limiter==3.8.0
      - flask-login==0.6.3
      - flask-session==0.5.0
      - flask-sqlalchemy==2.5.1
      - flask-wtf==1.2.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-re2==1.1.20240702
      - googleapis-common-protos==1.65.0
      - greenlet==3.1.0
      - grpcio==1.66.1
      - gspread==6.2.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - idna==3.10
      - importlib-metadata==6.11.0
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jmespath==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - lazy-object-proxy==1.10.0
      - limits==3.13.0
      - linkify-it-py==2.0.3
      - lockfile==0.12.2
      - mako==1.3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - marshmallow-oneofschema==3.1.1
      - marshmallow-sqlalchemy==0.28.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - methodtools==0.4.7
      - more-itertools==10.5.0
      - multidict==6.1.0
      - mysql-connector-python==9.3.0
      - numpy==2.2.6
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-exporter-otlp-proto-http==1.27.0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - ordered-set==4.1.0
      - packaging==24.1
      - pandas==2.3.0
      - pathspec==0.12.1
      - pendulum==3.0.0
      - pluggy==1.5.0
      - prison==0.2.1
      - protobuf==4.25.4
      - psutil==6.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyjwt==2.9.0
      - pyodbc==5.2.0
      - pyparsing==3.2.3
      - python-daemon==3.0.1
      - python-dotenv==1.1.0
      - python-nvd3==0.16.0
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rich==13.8.1
      - rich-argparse==1.5.2
      - rpds-py==0.20.0
      - rsa==4.9.1
      - setproctitle==1.3.3
      - six==1.16.0
      - sniffio==1.3.1
      - sqlalchemy==1.4.54
      - sqlalchemy-jsonfield==1.0.2
      - sqlalchemy-utils==0.41.2
      - sqlparse==0.5.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - termcolor==2.4.0
      - text-unidecode==1.3
      - time-machine==2.15.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - unicodecsv==0.14.1
      - universal-pathlib==0.2.5
      - urllib3==1.26.20
      - werkzeug==2.2.3
      - wirerope==0.4.7
      - wrapt==1.16.0
      - wtforms==3.1.2
      - yarl==1.11.1
      - zipp==3.20.2
prefix: /home/duclu/miniconda3/envs/DWH_Cole
